# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6c423ef92fe77a1e0161dd93bb6be3fbac3f87505fc58735d36b1737af2ff0be89a4e2429866cc436ec306e0af5857f2ea26ca158c6b6cf6a33c98d54f55b2a

test:
  secret_key_base: 0ba596b71a4116915f9bf02edd113e6d32618d7e272f2acdbae7ee216bf1458bf25edb8acccac8077826b1061be253e601641194e7047c958a28ddd7c0681661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
